### ISSUE TITLE
SOHA DBMS select 절 '괄호' 사용되는 function 호출 시 결과가 나오지 않는 현상. 

### ISSUE THREAD

**Issue by kimdhe88** [sinsiway/data-studio#90]
- 괄호'()' 가 포함 된 function 사용 시 결과 데이터가 나오지 않는 현상. 
- alias를 스트링으로 주면 정상적으로 조회가 됨. 

![컬럼명에 괄호 있을 때 결과 나오지 않는 현상](https://user-images.githubusercontent.com/41457962/88607781-0a63dd00-d0bb-11ea-80d6-ae86ada67bcd.gif)

**Comment by sinsiway** [comment]
![image](https://user-images.githubusercontent.com/65210145/89857281-9b1bdc00-dbd6-11ea-9074-6cb4dc1845b1.png)
datatables 플러그인에서 ()를 예약어로 사용하고있어 나던 오류.
우회법 추가 하여 잘 나오도록 수정.
